file_format: "1"
id: 9key_makro_master_zmk
name: 9key Makro Master
type: shield
url: https://github.com/SinaSalvatrice/9key_makro_master_zmk
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
  - encoder
  - display
  - underglow
